#application name
appName: forum-solution

#CORS configuration
allowedOrigins: http://localhost:8080
allowedHeaders: X-Requested-With, Content-Type, Accept, Origin
allowedMethods: OPTIONS, GET, PUT, POST, DELETE, HEAD

#port settings
server:
  applicationConnectors:
    - type: http
      port: 9090

#database settings.
database:
  driverClass: org.h2.Driver
  user: sa
  password: 
  url: jdbc:h2:~/forum-db
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: false
    hibernate.format_sql: false
    hibernate.hbm2ddl.auto: validate